apiVersion: apps/v1
kind: Deployment
metadata:
  name: convoyslit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: convoyslit
  template:
    metadata:
      labels:
        app: convoyslit
    spec:
      containers:
        - image: gcr.io/buffer-data/convoyslit:hello
          imagePullPolicy: Always
          name: convoyslit
      restartPolicy: Always
