apiVersion: v1
kind: Service
metadata:
  name: convoyslit-service
  annotations:
    cloud.google.com/backend-config: '{"default": "convoyslit-backendconfig"}'
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  selector:
    app: convoyslit
  type: NodePort
